### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by kariljordan** [carpentries/instructor-feedback#2]
Copied and pasted from [here](https://github.com/carpentries/instructor-development/issues/70#issuecomment-427420773):

**Complete**
- [x]  Look at the pre-workshop survey. What questions are pertinent for you to know in order to plan your workshop? Add your comments to the document.
- [x] Look at the post-workshop survey. What questions are helpful to you to understand how your workshop went? Add your comments to the document.
- [x] Identify specifications to include in the pre/post-workshop survey report/dashboard for instructors.

**Upcoming**
- [ ]   Create/revise a mock-up script for the Instructor Feedback Report.
- [ ]   Get feedback from the community about the look and feel of the report.

**Mandatory for Kari, optional for others**
- [ ]   Create a ‘how to interpret your report’ document to send along with instructor feedback report.
- [ ]   Determine how workshop admins will incorporate this into their workflow.
- [ ]   Identify resources for coaching to supplement the report.
- [ ]   Write a blog post to launch the reports.

**Kari to complete with @fmichonneau**
- [ ]   Set up automation for the script and report generation.

**Comment by kariljordan** [comment]
Revised to-do list located in [this issue](https://github.com/carpentries/instructor-feedback/issues/4) (#2). Closing as we are finished and ready to release these reports.
